spring:
  application:
    name: the-commerce-toy

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/toy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    com.commerce.toy: debug
---
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver